[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
tempo = "https://eng:aphex-twin-jeff-mills@rpc.mainnet.tempo.xyz"
tempo-testnet = "https://rpc.moderato.tempo.xyz"
localhost = "http://127.0.0.1:8545"
